name: Rclone Auto Transfer
on:
  repository_dispatch:`
    types: [add]

jobs:
  add:
  runs-on: ubuntu-latest
  steps:
  - name: Setup Rclone
    uses: AnimMouse/setup-rclone@v1
    with:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
      
  - run: rclone copy source:sourcepath dest:destpath
